### ISSUE TITLE
Gradle shows unknown property LaunchMinecraftServerTask for extension 'minecraftServerConfig'.

### ISSUE THREAD

**Issue by qyl27** [sya-ri/minecraft-server-gradle-plugin#6]
## 🐛 Describe the bug
When I use this Gradle plugin as README.md. Gradle shows: groovy.lang.MissingPropertyException: Could not get unknown property 'LaunchMinecraftServerTask' for extension 'minecraftServerConfig' of type dev.s7a.gradle.minecraft.server.MinecraftServerConfig.

## ⚠️ Current behavior
Gradle shows: groovy.lang.MissingPropertyException: Could not get unknown property 'LaunchMinecraftServerTask' for extension 'minecraftServerConfig' of type dev.s7a.gradle.minecraft.server.MinecraftServerConfig.

## ✅ Expected behavior
It should find LaunchMinecraftServerTask correctly.

## 💣 Steps to reproduce
Use this Gradle plugin as the README.md in this project.  
My config is:  
```groovy
minecraftServerConfig {
    jarUrl.set(LaunchMinecraftServerTask.JarUrl.Paper("1.19.2"))
    serverDirectory.set(projectDir.toPath().resolve("run").resolve("paper").toFile())
    agreeEula.set(true)
}
```

## 📱 Tech info
 - Device: N/A
 - OS: Windows 11
 - Library/App version: 1.2.0

**Comment by sya-ri** [comment]
Thank you for opening the issue. Please wait a minute.

**Comment by sya-ri** [comment]
All default tasks have been removed in [v2.0.0](https://github.com/sya-ri/minecraft-server-gradle-plugin/releases/v2.0.0). So there is no minecraftServerConfig.
